# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
# See https://github.com/esy/esy/pull/957, specifically:
# https://github.com/esy/esy/blob/15f593510ea078b4b392b931c9572bc07a306119/scripts/install-esy.sh

---
- name: Prepare esy installation
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/tmp/esy-release"
    - "/tmp/esy-solve-cudf-release"
    - "{{ esy_prefix }}/bin"
    - "{{ esy_prefix }}/lib/node_modules/esy-solve-cudf/"

- name: Download esy
  get_url:
    url: "https://registry.npmjs.org/esy/-/esy-{{ esy_target_version }}.tgz"
    dest: "/tmp/esy-release/esy-{{ esy_target_version }}.tgz"
    checksum: "sha256:f2cec5e6556172141bb399d1dcef7db4b9d881b0bed9c9749c0eebd95584b739"
    timeout: 120
  retries: 3

- name: Download esy_solve_cudf
  get_url:
    url: "https://registry.npmjs.org/esy-solve-cudf/-/esy-solve-cudf-0.1.10.tgz"
    dest: "/tmp/esy-solve-cudf-release/esy-solve-cudf-0.1.10.tgz"
    checksum: "sha256:3cfb233e5536fe555ff1318bcff241481c8dcbe1edc30b5f97e2366134d3f234"
    timeout: 120
  retries: 3

- name: Unarchive esy
  unarchive:
    src: "/tmp/esy-release/esy-{{ esy_target_version }}.tgz"
    dest: "/tmp/esy-release/"
    remote_src: yes

- name: Unarchive esy_solve_cudf
  unarchive:
    src: "/tmp/esy-solve-cudf-release/esy-solve-cudf-0.1.10.tgz"
    dest: "/tmp/esy-solve-cudf-release/"
    remote_src: yes

- name: Copy esy package.json
  copy:
    src: "/tmp/esy-release/package/package.json"
    dest: "{{ esy_prefix }}/"
    remote_src: yes

- name: Copy esy esyInstallRelease.js
  copy:
    src: "/tmp/esy-release/package/platform-linux/_build/default/bin/esyInstallRelease.js"
    dest: "{{ esy_prefix }}/bin/"
    remote_src: yes

- name: Copy esy default
  copy:
    src: "/tmp/esy-release/package/platform-linux/_build/default"
    dest: "{{ esy_prefix }}/lib/"
    remote_src: yes

- name: Copy esy_solve_cudfy package.json
  copy:
    src: "/tmp/esy-solve-cudf-release/package/package.json"
    dest: "{{ esy_prefix }}/lib/node_modules/esy-solve-cudf/"
    remote_src: yes

- name: Copy esy_solve_cudf exe
  copy:
    src: "/tmp/esy-solve-cudf-release/package/platform-linux/esySolveCudfCommand.exe"
    dest: "{{ esy_prefix }}/lib/node_modules/esy-solve-cudf/"
    remote_src: yes

- name: Apply esy permissions
  file:
    mode: 0555
    path: "{{ item }}"
  with_items:
    - "{{ esy_prefix }}/lib/default/bin/esy.exe"
    - "{{ esy_prefix }}/lib/default/esy-build-package/bin/esyBuildPackageCommand.exe"
    - "{{ esy_prefix }}/lib/default/esy-build-package/bin/esyRewritePrefixCommand.exe"

- name: Create esy symbolic links
  file:
    src: "{{ esy_prefix }}/lib/default/bin/esy.exe"
    dest: "/usr/local/bin/esy"
    force: yes
    state: link

- name: Cleanup esy installation
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - esy-release
    - esy-solve-cudf-release
