// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef _ENCLIBC_LIMITS_H
#define _ENCLIBC_LIMITS_H

#include "bits/common.h"

#define ENCLIBC_SCHAR_MIN (-128)
#define ENCLIBC_SCHAR_MAX 127
#define ENCLIBC_UCHAR_MAX 255
#define ENCLIBC_CHAR_MIN (-128)
#define ENCLIBC_CHAR_MAX 127
#define ENCLIBC_CHAR_BIT 8
#define ENCLIBC_SHRT_MIN (-1 - 0x7fff)
#define ENCLIBC_SHRT_MAX 0x7fff
#define ENCLIBC_USHRT_MAX 0xffff
#define ENCLIBC_INT_MIN (-1 - 0x7fffffff)
#define ENCLIBC_INT_MAX 0x7fffffff
#define ENCLIBC_UINT_MAX 0xffffffffU
#define ENCLIBC_LONG_MAX 0x7fffffffffffffffL
#define ENCLIBC_LONG_MIN (-ENCLIBC_LONG_MAX - 1)
#define ENCLIBC_ULONG_MAX (2UL * ENCLIBC_LONG_MAX + 1)
#define ENCLIBC_LLONG_MAX 0x7fffffffffffffffLL
#define ENCLIBC_LLONG_MIN (-ENCLIBC_LLONG_MAX - 1)
#define ENCLIBC_ULLONG_MAX (2ULL * ENCLIBC_LLONG_MAX + 1)

#if defined(ENCLIBC_NEED_STDC_NAMES)

#define SCHAR_MIN ENCLIBC_SCHAR_MIN
#define SCHAR_MAX ENCLIBC_SCHAR_MAX
#define UCHAR_MAX ENCLIBC_UCHAR_MAX
#define CHAR_MIN ENCLIBC_CHAR_MIN
#define CHAR_MAX ENCLIBC_CHAR_MAX
#define CHAR_BIT ENCLIBC_CHAR_BIT
#define SHRT_MIN ENCLIBC_SHRT_MIN
#define SHRT_MAX ENCLIBC_SHRT_MAX
#define USHRT_MAX ENCLIBC_USHRT_MAX
#define INT_MIN ENCLIBC_INT_MIN
#define INT_MAX ENCLIBC_INT_MAX
#define UINT_MAX ENCLIBC_UINT_MAX
#define LONG_MAX ENCLIBC_LONG_MAX
#define LONG_MIN ENCLIBC_LONG_MIN
#define ULONG_MAX ENCLIBC_ULONG_MAX
#define LLONG_MAX ENCLIBC_LLONG_MAX
#define LLONG_MIN ENCLIBC_LLONG_MIN
#define ULLONG_MAX ENCLIBC_ULLONG_MAX

#endif /* defined(ENCLIBC_NEED_STDC_NAMES) */

#endif /* _ENCLIBC_LIMITS_H */
