// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>

// Include the untrusted sgxtest header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the sgxtest.edl file.
#include "sgxtest_u.h"

// This is the function that the enclave will call back into to
// print a message.
void host_sgxtest()
{
    fprintf(stdout, "Enclave called into host to print: Hello World!\n");
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;

    if (argc != 2)
    {
        fprintf(stderr, "Usage: %s enclave_image_path\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_sgxtest_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_sgxtest_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Call into the enclave
    int enclave_ret;
    result = enclave_sgxtest(enclave, &enclave_ret);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_sgxtest failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }
    if (enclave_ret != 0)
    {
        fprintf(stderr, "Error: enclave failed on making an ocall\n");
        goto exit;
    }

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
