# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
cmake_target_version: "3.13.1"
clang_target_version: "7.1.0"
esy_target_version: "0.5.8"
esy_prefix: "/usr/local/lib/esy"

apt_packages:
  - "curl"
  - "clang-7"
  - "clang-format-7"
  - "make"
  - "ninja-build"
  - "shellcheck"
  - "gcc"
  - "g++"
  - "gdb"
  - "libssl-dev"
  - "openssl"
  - "pkg-config"
  - "apt-transport-https"
  - "autoconf"
  - "doxygen"
  - "graphviz"
  - "libexpat1-dev"
  - "libtool"
  - "subversion"
  - "libcurl4-openssl-dev"
  - "libx11-dev"
  - "libncurses5-dev"

apt_arm_packages:
  - "gcc-arm-linux-gnueabi"
  - "gcc-arm-linux-gnueabihf"
  - "gcc-aarch64-linux-gnu"
  - "g++-aarch64-linux-gnu"
  - "python-crypto"
  - "libc6-dev:arm64"
  - "libssl-dev:arm64"
  - "libfdt1"
  - "openssh-client"
  - "sshpass"

validation_directories:
  - "/usr/share/libtool"

validation_files:
  - "/usr/lib/x86_64-linux-gnu/libssl.so"

validation_binaries:
  - "/usr/bin/make"
  - "/usr/local/bin/cmake"
  - "/usr/local/bin/ccmake"
  - "/usr/local/bin/cpack"
  - "/usr/local/bin/ctest"
  - "/usr/local/bin/esy"
  - "/usr/bin/dot"
  - "/usr/bin/gcc"
  - "/usr/bin/g++"
  - "/usr/bin/gdb"
  - "/usr/bin/autoconf"
  - "/usr/bin/libtoolize"
  - "/usr/bin/doxygen"
  - "/usr/bin/openssl"
  - "/usr/bin/pkg-config"
  - "/usr/bin/clang-7"
  - "/usr/bin/shellcheck"
  - "/usr/bin/git"
  - "/usr/bin/svn"
