# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  become: yes
  tasks:
    - import_role:
        name: linux/openenclave
        tasks_from: esy-setup.yml
        vars_from: ubuntu.yml
